/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tugas.praktikum.pkg2;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;



//import javax.swing.JOptionPane;


/**
 *
 * @author ArumNenden
 */



public class TP2 extends javax.swing.JFrame {

    /**
     * Creates new form TP2
     */
    /*
    private Statement St;
    private ResultSet Rs;
    private Connection Con;
    private String sql="";
    */
    /*
    Cara 2:
    public static Connection con;
    public static Statement stm;
    */
    private static Connection mysqlkonek;
    
    public TP2() {
        initComponents();
        awal.setVisible(true);// biar munculin bagian selamat datang
        Tabel.setVisible(false);
        Info.setVisible(false);
        Form.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDasar = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        buttonForm = new javax.swing.JButton();
        buttonTable = new javax.swing.JButton();
        buttonInfo = new javax.swing.JButton();
        awal = new javax.swing.JPanel();
        ucapan = new javax.swing.JLabel();
        Form = new javax.swing.JPanel();
        Merek = new javax.swing.JLabel();
        Warna = new javax.swing.JLabel();
        Plat = new javax.swing.JLabel();
        Jenis = new javax.swing.JLabel();
        isiMerk = new javax.swing.JTextField();
        isiPlat = new javax.swing.JTextField();
        isiWarna = new javax.swing.JTextField();
        isiJenis = new javax.swing.JComboBox<>();
        Submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Data = new javax.swing.JTable();
        Info = new javax.swing.JPanel();
        Nama = new javax.swing.JLabel();
        Nim = new javax.swing.JLabel();
        isi = new javax.swing.JLabel();
        isi2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(0, 0, 0));

        judul.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 153, 0));
        judul.setText("Data Mobil");

        buttonForm.setBackground(new java.awt.Color(255, 153, 0));
        buttonForm.setText("Form");
        buttonForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFormActionPerformed(evt);
            }
        });

        buttonTable.setBackground(new java.awt.Color(255, 153, 0));
        buttonTable.setText("Table");
        buttonTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTableActionPerformed(evt);
            }
        });

        buttonInfo.setBackground(new java.awt.Color(255, 153, 0));
        buttonInfo.setText("Info");
        buttonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(buttonForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(buttonTable)
                .addGap(40, 40, 40)
                .addComponent(buttonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judul)
                .addGap(18, 18, 18)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(buttonInfo)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonForm)
                            .addComponent(buttonTable))
                        .addGap(20, 20, 20))))
        );

        ucapan.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        ucapan.setText("Selamat Datang :)");

        javax.swing.GroupLayout awalLayout = new javax.swing.GroupLayout(awal);
        awal.setLayout(awalLayout);
        awalLayout.setHorizontalGroup(
            awalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, awalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ucapan)
                .addGap(76, 76, 76))
        );
        awalLayout.setVerticalGroup(
            awalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(awalLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(ucapan)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        Merek.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Merek.setText("Merek");

        Warna.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Warna.setText("Warna");

        Plat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Plat.setText("Plat");

        Jenis.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Jenis.setText("Jenis");

        isiMerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiMerkActionPerformed(evt);
            }
        });

        isiPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiPlatActionPerformed(evt);
            }
        });

        isiJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biasa", "Sport", "Balap", "Truck" }));

        Submit.setBackground(new java.awt.Color(255, 153, 0));
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        jLabel1.setText("Isi Data :");

        javax.swing.GroupLayout FormLayout = new javax.swing.GroupLayout(Form);
        Form.setLayout(FormLayout);
        FormLayout.setHorizontalGroup(
            FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(FormLayout.createSequentialGroup()
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FormLayout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(Merek, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Plat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Warna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(isiJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(isiMerk, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addComponent(isiPlat)
                        .addComponent(isiWarna)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        FormLayout.setVerticalGroup(
            FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Merek)
                    .addComponent(isiMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Plat)
                    .addComponent(isiPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Warna)
                    .addComponent(isiWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jenis)
                    .addComponent(isiJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(Submit)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(375, 64));

        Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Merek", "Plat", "Warna", "Jenis"
            }
        ));
        jScrollPane1.setViewportView(Data);

        javax.swing.GroupLayout TabelLayout = new javax.swing.GroupLayout(Tabel);
        Tabel.setLayout(TabelLayout);
        TabelLayout.setHorizontalGroup(
            TabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );
        TabelLayout.setVerticalGroup(
            TabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        Nama.setText("Nama :");

        Nim.setText("Nim    :");

        isi.setText("Nenden Citra S.N");

        isi2.setText("1908589");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/rsz_1rsz_1face1.jpg"))); // NOI18N

        javax.swing.GroupLayout InfoLayout = new javax.swing.GroupLayout(Info);
        Info.setLayout(InfoLayout);
        InfoLayout.setHorizontalGroup(
            InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nim, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isi2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        InfoLayout.setVerticalGroup(
            InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(isi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nim)
                    .addComponent(isi2))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout PanelDasarLayout = new javax.swing.GroupLayout(PanelDasar);
        PanelDasar.setLayout(PanelDasarLayout);
        PanelDasarLayout.setHorizontalGroup(
            PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(awal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Tabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Info, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDasarLayout.setVerticalGroup(
            PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDasarLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(awal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDasarLayout.createSequentialGroup()
                    .addGap(0, 150, Short.MAX_VALUE)
                    .addComponent(Form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDasarLayout.createSequentialGroup()
                    .addGap(0, 151, Short.MAX_VALUE)
                    .addComponent(Tabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDasarLayout.createSequentialGroup()
                    .addContainerGap(104, Short.MAX_VALUE)
                    .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelDasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isiMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiMerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiMerkActionPerformed

    private void buttonFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFormActionPerformed
        // TODO add your handling code here:
        Form.setVisible(true);// agar mucul si panel form
        Info.setVisible(false);
        Tabel.setVisible(false);
        awal.setVisible(false);
    }//GEN-LAST:event_buttonFormActionPerformed

    private void buttonTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTableActionPerformed
        // TODO add your handling code here:
        Form.setVisible(false);
        Info.setVisible(false);
        Tabel.setVisible(true);//agar muncul di panel tabel
        awal.setVisible(false);
        
        try {
            String sql = "SELECT * FROM manusia;";
            Class.forName("com.mysql.cj.jdbc.Driver");// Menentukan Driver Database
            Connection koneksi  = DriverManager.getConnection("jdbc:mysql://localhost:3306/tugas_praktikum2", "root", ""); //untuk mengkoneksi DB ke driver
            Statement sta = koneksi.createStatement();
            ResultSet resu   = sta.executeQuery(sql);

            DefaultTableModel dtm = (DefaultTableModel) Data.getModel();
        dtm.setRowCount(0);
        String [] data = new String[5];
        
       
        while(resu.next()) {
            data[0] = resu.getString("No");
            data[1] = resu.getString("Merk");
            data[2] = resu.getString("Plat");
            data[3] = resu.getString("Warna");
            data[4] = resu.getString("Jenis");
            dtm.addRow(data);
           
        }
        }
        catch (Exception e) {
           System.out.println("eror");
        }

        /*
        try
        {
            
            Class.forName("com.mysql.cj.jdbc.Driver");// Menentukan Driver Database
            Connection koneksi  = DriverManager.getConnection("jdbc:mysql://localhost:3306/tugas_praktikum2", "root", ""); //untuk mengkoneksi DB ke driver
            String sql = "SELECT * FROM manusia" + "(Merk, Plat, Warna, Jenis) VALUES" + " (?, ?, ?, ?)";           
            PreparedStatement ps = koneksi.prepareStatement(sql);  
        }
        catch (Exception e){
            System.out.println("eror");
        } 
        */ 
        
        
        
    }//GEN-LAST:event_buttonTableActionPerformed

    private void buttonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInfoActionPerformed
        // TODO add your handling code here:
        Form.setVisible(false);
        Info.setVisible(true);// agar muncul si panel info
        Tabel.setVisible(false);
        awal.setVisible(false);
    }//GEN-LAST:event_buttonInfoActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String merk = isiMerk.getText();// untuk hubungin ke text field 
        String plat = isiPlat.getText();// untuk hubungin ke text field
        String warna = isiWarna.getText();// untuk hubungin ke text field
        String jenis = isiJenis.getSelectedItem().toString();// untuk hubungin ke comboBox
       
        try {                       
                Class.forName("com.mysql.cj.jdbc.Driver");// Menentukan Driver Database
                Connection koneksi  = DriverManager.getConnection("jdbc:mysql://localhost:3306/tugas_praktikum2", "root", ""); //untuk mengkoneksi DB ke driver
                String sql = "INSERT INTO manusia" + "(Merk, Plat, Warna, Jenis) VALUES" + " (?, ?, ?, ?)";           
                PreparedStatement ps = koneksi.prepareStatement(sql);
                ps.setString(1, merk);
                ps.setString(2, plat);
                ps.setString(3, warna);
                ps.setString(4, jenis);
                ps.executeUpdate();
                
                System.out.println("Berhasil");
            
            
           
        }
        catch (Exception e){
            System.out.println("eror");
        }       
    }//GEN-LAST:event_SubmitActionPerformed

    private void isiPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiPlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiPlatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TP2().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Data;
    private javax.swing.JPanel Form;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Info;
    private javax.swing.JLabel Jenis;
    private javax.swing.JLabel Merek;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nim;
    private javax.swing.JPanel PanelDasar;
    private javax.swing.JLabel Plat;
    private javax.swing.JButton Submit;
    private javax.swing.JPanel Tabel;
    private javax.swing.JLabel Warna;
    private javax.swing.JPanel awal;
    private javax.swing.JButton buttonForm;
    private javax.swing.JButton buttonInfo;
    private javax.swing.JButton buttonTable;
    private javax.swing.JLabel isi;
    private javax.swing.JLabel isi2;
    private javax.swing.JComboBox<String> isiJenis;
    private javax.swing.JTextField isiMerk;
    private javax.swing.JTextField isiPlat;
    private javax.swing.JTextField isiWarna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel ucapan;
    // End of variables declaration//GEN-END:variables
}
